//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP4ME.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class bom_table
    {
        public string type { get; set; }
        public string component { get; set; }
        public string component_description { get; set; }
        public float quantity_per { get; set; }
        public string unit_of_measure { get; set; }
        public System.DateTime effective_from { get; set; }
        public System.DateTime effective__through { get; set; }
        public decimal cost_of_unit_of_measure { get; set; }
        public decimal bom_cost { get; set; }
        public decimal scrap_percent { get; set; }
        public decimal scrap_cost { get; set; }
        public decimal extended_cost { get; set; }
        public int version { get; set; }
        public string item_code { get; set; }
        public string item_number { get; set; }
        public bool engineering_change_order { get; set; }
        public int bom_id { get; set; }
        public int parent_bom_id { get; set; }
    }
}
