//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP4ME.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_order
    {
        public string customer_name { get; set; }
        public System.DateTime required_date { get; set; }
        public string so_number { get; set; }
        public string item_code { get; set; }
        public string name { get; set; }
        public string unit { get; set; }
        public decimal unit_cost { get; set; }
        public string description { get; set; }
        public int quantity { get; set; }
        public Nullable<int> quantity_received { get; set; }
        public Nullable<int> back_ordered { get; set; }
        public string attachment { get; set; }
        public string upload_image { get; set; }
        public string user { get; set; }
        public int level { get; set; }
    }
}
